[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.5"
num-traits = "0.2.19"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
